name: test_deploy

# Controls when the workflow will run
on:
  release:
    types: [published, released]

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(echo "$REF" | awk -F '/' '{print $NF}' | tr -d 'v')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        env:
          REF: ${{ github.ref }}

      - name: update_version
        run: sed -i "s/version.*/version = \"$VERSION\"/" pyproject.toml
        env:
          VERSION: ${{ steps.extract_version.outputs.version }}

      - name: Upload pyproject
        uses: actions/upload-artifact/@v4
        with:
          name: pyproject
          path: pyproject.toml

  deploy_prod:
    runs-on: ubuntu-latest
    needs: [update_version]
    if: ${{ !github.event.release.prerelease }}
    steps:
      - name: Update pyproject
        uses: actions/download-artifact@v4
        with:
          name: pyproject

      - name: Print version
        run: |
          cat pyproject.toml | grep version

  deploy_test:
    runs-on: ubuntu-latest
    needs: [update_version]
    if: ${{ github.event.release.prerelease }}
    steps:
      - name: Update pyproject
        uses: actions/download-artifact@v4
        with:
          name: pyproject

      - name: Print version
        run: |
          cat pyproject.toml | grep version
